In [4]:
# Tensor（张量），NumPy 的 ndarray
from __future__ import print_function

In [1]:
import torch

In [5]:
x=torch.empty(5,3)
print(x)

tensor([[4.7423e+30, 4.7393e+30, 9.5461e-01],
        [4.4377e+27, 1.7975e+19, 4.6894e+27],
        [7.9463e+08, 3.2604e-12, 2.6209e+20],
        [4.1641e+12, 1.9434e-19, 3.0881e+29],
        [6.3828e+28, 1.4603e-19, 7.7179e+28]])


In [7]:
# 创建一个随机初始化矩阵
x=torch.rand(5,3)
print(x)

tensor([[0.4066, 0.7591, 0.8275],
        [0.9739, 0.6145, 0.5907],
        [0.3834, 0.5699, 0.3305],
        [0.0403, 0.7996, 0.1233],
        [0.9444, 0.1741, 0.8302]])


In [8]:
# 构造一个填满  0  且数据类型为  long  的矩阵
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
# 直接从数据构造张量
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
# 或根据现有的  tensor 建立新的  tensor 。除非用户提供新的值，否则这些方法将重用输入张量的属性，例如 dtype 等：
x=x.new_ones(5,3,dtype=torch.double)# new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x=torch.randn_like(x,dtype=torch.float)# 重载 dtype!
print(x)# 结果size一致

tensor([[-1.2912,  0.0624,  1.0032],
        [ 1.8949,  0.8134,  0.7954],
        [ 1.4047,  0.4766,  0.6639],
        [-0.0123, -1.9617, -0.2607],
        [ 0.6702, -0.2979, -0.1987]])


In [13]:
# 获取张量的形状：
print(x.size())
# 注意：torch.Size 本质上还是 tuple ，所以支持 tuple 的一切操作。

torch.Size([5, 3])


In [ ]:
# 运算

In [14]:
# 加法：形式一
y=torch.rand(5,3)


tensor([[-0.9041,  0.2302,  1.9319],
        [ 2.0084,  1.0080,  1.2983],
        [ 1.9168,  1.1895,  1.1673],
        [ 0.8150, -1.1821, -0.0899],
        [ 1.5534,  0.6411,  0.0693]])


In [15]:
print(y)

tensor([[0.3870, 0.1679, 0.9286],
        [0.1135, 0.1946, 0.5029],
        [0.5121, 0.7130, 0.5035],
        [0.8273, 0.7797, 0.1708],
        [0.8832, 0.9390, 0.2680]])


In [16]:
print(x+y)

tensor([[-0.9041,  0.2302,  1.9319],
        [ 2.0084,  1.0080,  1.2983],
        [ 1.9168,  1.1895,  1.1673],
        [ 0.8150, -1.1821, -0.0899],
        [ 1.5534,  0.6411,  0.0693]])


In [17]:
# 加法：形式二
print(torch.add(x, y))

tensor([[-0.9041,  0.2302,  1.9319],
        [ 2.0084,  1.0080,  1.2983],
        [ 1.9168,  1.1895,  1.1673],
        [ 0.8150, -1.1821, -0.0899],
        [ 1.5534,  0.6411,  0.0693]])


In [18]:
# 加法：给定一个输出张量作为参数
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-0.9041,  0.2302,  1.9319],
        [ 2.0084,  1.0080,  1.2983],
        [ 1.9168,  1.1895,  1.1673],
        [ 0.8150, -1.1821, -0.0899],
        [ 1.5534,  0.6411,  0.0693]])


In [19]:
# 加法：原位/原地操作（in-place
#adds x to y
y.add(x)
print(y)
# 注意：任何一个就地改变张量的操作后面都固定一个  _  。例如 x.copy_（y）， x.t_（） 将更改x

tensor([[0.3870, 0.1679, 0.9286],
        [0.1135, 0.1946, 0.5029],
        [0.5121, 0.7130, 0.5035],
        [0.8273, 0.7797, 0.1708],
        [0.8832, 0.9390, 0.2680]])


In [20]:
# 可以使用像标准的 NumPy 一样的各种索引操作：
print(x[:,1])

# tensor([[-1.2912,  0.0624,  1.0032],
        # [ 1.8949,  0.8134,  0.7954],
        # [ 1.4047,  0.4766,  0.6639],
        # [-0.0123, -1.9617, -0.2607],
        # [ 0.6702, -0.2979, -0.1987]])

tensor([ 0.0624,  0.8134,  0.4766, -1.9617, -0.2979])


In [21]:
# 改变形状：如果想改变形状，可以使用  torch.view
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)# the size -1 is inferred from other dimensions
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [23]:
# 如果是仅包含一个元素的 tensor，可以使用   .item（）  来得到对应的 python 数值
x=torch.randn(1)
print(x)
print(x.item())
# 后续阅读： 超过100种 tensor的运算操作，包括转置，索引，切片，数学运算，线性代数，随机数等，具体访问

tensor([-1.9829])
-1.9828834533691406


In [24]:
# 将 torch 的 Tensor 转换为 NumPy 数组
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [25]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [26]:
# 看 NumPy 细分是如何改变里面的值的
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
# 将 NumPy 数组转化为Torch张量
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [29]:
# CUDA上的张量
if torch.cuda.is_available():
    device=torch.device("cuda")# a CUDA device object
    y=torch.ones_like(x,device=device)# 直接在GPU上创建tensor
    x=x.to(devices) # 或者使用`.to("cuda")`方法
    z=x+y
    print(z)
    print(z.to("cpu",torch.double)) # `.to`也能在移动时改变dtype
else:
    print("暂时不支持CUDA")

暂时不支持CUDA
