In [24]:
import torch

In [25]:
import torchvision

In [26]:
import torch.nn as nn

In [27]:
from torch.autograd import Variable # torch 中 Variable 模块

In [28]:
import torch.optim as optim

In [29]:
x=Variable(torch.randn(5,5))

In [30]:
print(x)

tensor([[ 0.3242,  1.3601, -1.2184,  0.7560,  1.9978],
        [-0.6877, -0.3743,  0.2780, -1.2340,  1.2050],
        [ 0.8155,  1.5181,  0.4653, -0.2964,  0.1167],
        [-0.3351, -2.0172,  1.1775, -0.5225,  1.0591],
        [ 1.7305, -0.5711, -0.7563,  1.2339, -0.3530]])


In [31]:
y=Variable(torch.randn(5,5))
print(y)

tensor([[ 1.0474, -1.3665, -0.1760,  0.4986,  0.6361],
        [-0.1689, -0.8364,  0.9586,  0.3683, -0.0436],
        [ 0.7129,  0.8253,  0.1222,  2.0919, -0.2164],
        [-0.8105,  0.5471, -2.0739,  1.2057,  1.2774],
        [-1.0988,  0.3573, -0.6263, -1.5799, -1.1115]])


In [32]:
z=Variable(torch.randn(5,5),requires_grad=True)
print(z)

tensor([[-1.2822,  0.2867,  0.0456,  0.7663,  1.5003],
        [-0.0366, -0.0222, -1.7171, -0.7819, -1.6373],
        [ 1.0584, -0.3390, -1.1583, -0.4284,  0.3642],
        [-0.6551, -0.9890,  0.8624, -0.2975, -0.0070],
        [ 0.3979, -0.5377,  0.9756, -2.3150,  1.2445]], requires_grad=True)


In [33]:
a=x+y

In [34]:
print(a.requires_grad)

False


In [35]:
b=a+z

In [36]:
print(b.requires_grad)

True


In [18]:
model=torchvision.models.resnet18(pretrained=True)

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /Users/smart/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth



ConnectionResetError: [Errno 54] Connection reset by peer

In [ ]:
for param in model.parameters():
    param.requires_grad=False

In [ ]:
model.fc=nn.Linear(512,100)


In [ ]:
optimizer=optim.SGD(model.fc.parameters().lr=1e-2,momentum=0.9)